#!/bin/bash
docker-compose run --service-ports $1
if [ $1 = "tests" ]; then
docker exec musicmanager_pgsql-db_1 bash -c "psql -U postgres -c 'drop database tests_db' "
docker exec musicmanager_pgsql-db_1 bash -c "psql -U postgres -c 'create database tests_db' "
bash
fi