"""required fields setted in users and music tables

Revision ID: 36e827e707ba
Revises: 5aeb721feca9
Create Date: 2020-10-30 00:12:04.989172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e827e707ba'
down_revision = '5aeb721feca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'artist',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('music', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('music', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('music', 'artist',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
