"""user.id on delete set CASCADE

Revision ID: 55a4eeecf6ee
Revises: 65068c20130e
Create Date: 2020-10-30 02:20:23.689815

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "55a4eeecf6ee"
down_revision = "65068c20130e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("music_user_id_fkey", "music", type_="foreignkey")
    op.create_foreign_key(
        None, "music", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "music", type_="foreignkey")
    op.create_foreign_key("music_user_id_fkey", "music", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###
