"""user_id included into Music

Revision ID: 5aeb721feca9
Revises: 23c583c455e8
Create Date: 2020-10-30 00:09:28.267353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aeb721feca9'
down_revision = '23c583c455e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'music', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'music', type_='foreignkey')
    op.drop_column('music', 'user_id')
    # ### end Alembic commands ###
