"""user.id ondelete CASCADE

Revision ID: 65068c20130e
Revises: 782ba92264d7
Create Date: 2020-10-30 02:17:45.472144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65068c20130e'
down_revision = '782ba92264d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
