"""user_id from music table is required

Revision ID: 782ba92264d7
Revises: 36e827e707ba
Create Date: 2020-10-30 00:16:43.017777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782ba92264d7'
down_revision = '36e827e707ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
