"""Creating user table

Revision ID: 80acd462cca4
Revises: 0ffc1e603532
Create Date: 2020-10-28 02:23:57.905297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "80acd462cca4"
down_revision = "0ffc1e603532"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("password", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
