"""field password max length from users table changed to 256

Revision ID: 8d652dc8ef0c
Revises: bad356c8be4c
Create Date: 2020-10-28 11:35:01.791697

"""


# revision identifiers, used by Alembic.
revision = "8d652dc8ef0c"
down_revision = "bad356c8be4c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
